### ISSUE TITLE
NameError: global name 'gen_self_signed_ssl' is not defined

### ISSUE THREAD

**Issue by hequan2017** [jimmy201602/django-gateone#1]
^C[root@python django-gateone-master]# python  manage.py runserver 
Unhandled exception in thread started by <function wrapper at 0x385a320>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/channels/management/commands/runserver.py", line 41, in inner_run
    self.channel_layer = channel_layers[DEFAULT_CHANNEL_LAYER]
  File "/usr/lib/python2.7/site-packages/channels/asgi.py", line 53, in __getitem__
    self.backends[key] = self.make_backend(key)
  File "/usr/lib/python2.7/site-packages/channels/asgi.py", line 48, in make_backend
    routing=routing,
  File "/usr/lib/python2.7/site-packages/channels/asgi.py", line 80, in __init__
    self.router = Router(self.routing)
  File "/usr/lib/python2.7/site-packages/channels/routing.py", line 25, in __init__
    self.root = Include(routing)
  File "/usr/lib/python2.7/site-packages/channels/routing.py", line 201, in __init__
    self.routing = Router.resolve_routing(routing)
  File "/usr/lib/python2.7/site-packages/channels/routing.py", line 73, in resolve_routing
    routing = getattr(importlib.import_module(module_name), variable_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/django-gateone-master/django_gateone/routing.py", line 2, in <module>
    from applications.server import ApplicationWebSocket
  File "/root/django-gateone-master/applications/server.py", line 398, in <module>
    from applications.auth.authentication import NullAuthHandler, KerberosAuthHandler
  File "/root/django-gateone-master/applications/auth/authentication.py", line 86, in <module>
    from applications.locale import get_translation
  File "/root/django-gateone-master/applications/locale.py", line 18, in <module>
    from applications.configuration import get_settings
  File "/root/django-gateone-master/applications/configuration.py", line 31, in <module>
    logger = go_logger(None)
  File "/root/django-gateone-master/applications/log.py", line 370, in go_logger
    if not define_options()['log_file_prefix'] or define_options()['logging'].upper() == 'NONE':
  File "/root/django-gateone-master/applications/log.py", line 204, in define_options
    gen_self_signed_ssl(path=ssl_base)
NameError: global name 'gen_self_signed_ssl' is not defined

**Comment by jimmy201602** [comment]
正在修复....

**Comment by jimmy201602** [comment]
bug fixed
